language: python
python:
  - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-dev python-sip qt-sdk python-qt4
 - git submodule update --init --recursive
install: "pip install -r requirements.txt"
script: nosetests -w src/shelfari
notifications:
  email:
    recipients:
      - casey.duquette@gmail.com
